#
# This is the Serif config file. It must be a valid YAML document.
#
# For information on which values are available here, see the README.
#
admin:
  username: changethisusername
  password: changethispassword
permalink: /:title
archive:
  enabled: yes
  url_format: /archive/:year/:month