# This is the Serif config file. It must be a valid YAML document.
#
# Some configuration options:
#
#     admin:
#       username: [a username for the admin web interface]
#       password: [a password for the admin web interface]
#     permalink: [permalink format for generated posts]
#
# See the README for information on permalink formats.

admin:
  username: changethisusername
  password: changethispassword
permalink: /:title
archive:
  enabled: yes
  url_format: /archive/:year/:month